module.exports = {
  apps: [
    {
      name: "proxyService",
      script: "./services/proxy/server1.js",
      watch: true,
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 2000,
      ignore_watch: [".git", "./proxy/node_modules", "./store"],
    },
    {
      name: "authService",
      script: "./services/authService/server.js",
      watch: true,
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 2000,
      ignore_watch: [".git", "./services/authService/node_modules", "./store"],
    },
    {
      name: "clientsService",
      script: "./services/clientsService/src/server.js",
      watch: true,
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 2000,
      ignore_watch: [
        ".git",
        "./services/clientsService/node_modules",
        "./store",
      ],
    },
    {
      name: "discountsService",
      script: "./services/discountsService/src/server.js",
      watch: true,
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 2000,
      ignore_watch: [
        ".git",
        "./services/discountsService/node_modules",
        "./store",
      ],
    },
    {
      name: "docsService",
      script: "./services/docsService/src/index.js",
      watch: true,
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 2000,
      ignore_watch: [".git", "./services/docsService/node_modules", "./store"],
    },
    {
      name: "ordersService",
      script: "./services/ordersService/src/server.js",
      watch: true,
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 2000,
      ignore_watch: [
        ".git",
        "./services/ordersService/node_modules",
        "./store",
      ],
    },
    {
      name: "toolsService",
      script: "./services/toolsService/src/server.js",
      watch: true,
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 2000,
      ignore_watch: [".git", "./services/toolsService/node_modules", "./store"],
    },
  ],
};
